language: python

python:
  - "3.8"  # Specify the Python version you're using

# Commands to install dependencies
install:
  - pip install -r requirements.txt  # Install your dependencies

# Commands to run before your tests (e.g., migrations)
before_script:
  - python manage.py migrate  # Run database migrations

# Command to run tests
script:
  - pytest  # If you're using pytest
  # - python manage.py test  # If you prefer Django's built-in test framework
